### ISSUE TITLE
My Page - 자기가 본책 List 접속시 에러 

### ISSUE THREAD

**Issue by angie4u** [TeamReviewer/renosh#50]
![image](https://user-images.githubusercontent.com/16282358/92193745-02f6d700-eea4-11ea-986f-b60f8a4a4e59.png)
로그인 후 My Page에서 자기가 본 책 접속시 다음과 같은 Blank 화면 및 콘솔로그 창의 에러메세지를 확인할 수 있다.

**Comment by sleesm** [comment]
Container에 은지님의 item이 중복되어 있어서 그런 것 같습니다. 로그인 시에 생성되는 부분에서 에러가 생긴 것 같아 다시 확인해보도록 하겠습니다!!

**Comment by sleesm** [comment]
@angie4u 중복 item을 제거했는데 혹시 새로 로그인하고 테스팅 해보실 수 있나요?
로그인 관련 코드를 살펴보고 제 아이디로 테스팅했을 때는 item이 중복되어서 만들어지지 않았어서 다른 분들의 확인이 필요할 것 같습니다!!!

**Comment by sleesm** [comment]
mybooklist가 null인 상태일 때는 다음과 같이 아무것도 뜨지 않아서 그 문제는 아닌 것 같습니다.
![image](https://user-images.githubusercontent.com/60386794/92197186-01311180-eeac-11ea-8055-8cbeacd28a7e.png)

**Comment by sleesm** [comment]
해결했습니다!!!
https://github.com/TeamReviewer/renosh/pull/54

**Comment by sleesm** [comment]
해결했습니다!!! https://github.com/TeamReviewer/renosh/pull/54
